# Generated by Django 6.0.2 on 2026-03-15 14:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text="Category color (e.g., '#4CAF50' or 'green')", max_length=20)),
                ('icon', models.CharField(blank=True, default='tree', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Commodity Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, help_text='Scientific name if applicable', max_length=200)),
                ('summary', models.TextField(help_text='Brief description of the commodity')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('growing_seasons', models.CharField(blank=True, max_length=200)),
                ('harvest_period', models.CharField(blank=True, max_length=200)),
                ('market_value', models.CharField(blank=True, help_text="e.g., '₱50-80/kg'", max_length=100)),
                ('resource_count', models.IntegerField(default=0, help_text='Number of resources available')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_recently_updated', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon_image', models.ForeignKey(blank=True, help_text='Small icon/image for cards', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('main_image', models.ForeignKey(blank=True, help_text='Main commodity image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodities', to='commodities.commoditycategory')),
            ],
            options={
                'verbose_name_plural': 'Commodities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, default='AANR Commodities', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Explore our collection of Agriculture, Aquatic, and Natural Resources commodities. Find detailed information, market insights, and best practices for each commodity.')),
                ('hero_background', models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
