# Generated by Django 6.0.2 on 2026-03-15 14:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, default='AANR Knowledge Resources', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Explore our comprehensive collection of resources in Agriculture, Aquatic, and Natural Resources sectors.')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='file-text', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resource_type', models.CharField(choices=[('publication', 'Publication'), ('news', 'News'), ('event', 'Event'), ('project', 'Project'), ('technology', 'Technology'), ('training', 'Training/Seminar'), ('webinar', 'Webinar'), ('policy', 'Policy'), ('map', 'Map'), ('media', 'Media'), ('product', 'Product'), ('info_system', 'Information System/Website'), ('other', 'Other')], default='publication', max_length=50)),
                ('summary', models.TextField(blank=True, help_text='Brief description of the resource')),
                ('content', wagtail.fields.RichTextField(blank=True)),
                ('external_url', models.URLField(blank=True, help_text='Link to external resource if no file')),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='knowledge.resourcecategory')),
            ],
            options={
                'ordering': ['-is_featured', 'sort_order', '-created_at'],
            },
        ),
    ]
