# Generated by Django 6.0.2 on 2026-03-15 07:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='features_subtitle',
            field=models.CharField(blank=True, default='Discover the powerful tools and resources available to help you advance your work in the AANR sector', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_title',
            field=models.CharField(blank=True, default='Knowledge Hub Features', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_quote',
            field=models.TextField(blank=True, default='Harnessing knowledge to sustain Agriculture, Aquatic, and Natural Resources— empowering communities, preserving nature, and driving innovation for a resilient future.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True, default='Empowering communities through knowledge sharing and technological advancement in Agriculture, Aquatic, and Natural Resources sectors.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='AANR Knowledge Hub', max_length=200),
        ),
    ]
