# Generated by Django 6.0.2 on 2026-03-15 09:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, default='RAISE Western Mindanao', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Empowering agricultural communities through innovation, sustainability, and knowledge sharing', max_length=300)),
                ('knowledge_hub_title', models.CharField(blank=True, default='Knowledge Hub', max_length=200)),
                ('knowledge_hub_subtitle', models.CharField(blank=True, default='Project Foundation', max_length=200)),
                ('knowledge_hub_description', models.TextField(blank=True, default='Understanding the core purpose and goals that drive our mission forward')),
                ('rationale_title', models.CharField(blank=True, default='Program Rationale', max_length=200)),
                ('rationale_content', wagtail.fields.RichTextField(blank=True)),
                ('objectives_title', models.CharField(blank=True, default='Program Objectives', max_length=200)),
                ('general_objective_title', models.CharField(blank=True, default='General:', max_length=100)),
                ('general_objective', models.TextField(blank=True)),
                ('specific_objectives_title', models.CharField(blank=True, default='Specific:', max_length=100)),
                ('specific_objectives', wagtail.fields.RichTextField(blank=True, help_text='Enter each objective on a new line')),
                ('org_title', models.CharField(blank=True, default='Organizational Structure', max_length=200)),
                ('org_description', models.CharField(blank=True, default='Our streamlined structure ensures efficient implementation across all project components', max_length=200)),
                ('projects_title', models.CharField(blank=True, default='RAISE Projects', max_length=200)),
                ('projects_description', models.TextField(blank=True, default='Discover our innovative agricultural research initiatives and collaborative projects that are transforming the future of farming and rural development')),
                ('org_image', models.ForeignKey(blank=True, help_text='Upload the organizational structure image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('projects_image', models.ForeignKey(blank=True, help_text='Upload the projects image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
