# Generated by Django 6.0.2 on 2026-03-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqtopic',
            name='icon',
            field=models.CharField(blank=True, default='tag', max_length=50),
        ),
    ]
